[project]
name = "deepjudge-challenge"
version = "0.1.0"
description = ""
authors = [
    {name = "Nic Dorner",email = "nic.dorner@me.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]

[tool.poetry]
packages = [{include = "deepjudge_challenge", from = "src"}]


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
